version: '3.8'

services:
  # Banco de Dados
  db:
    image: mariadb:10.4
    container_name: lab-db
    environment:
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa_user
      MYSQL_PASSWORD: dvwa_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lab-net
    restart: unless-stopped

  # Web Vulnerável
  web:
    image: vulnerables/web-dvwa
    container_name: lab-dvwa
    environment:
      DVWA_DB_HOST: db
      DVWA_DB_USER: dvwa_user
      DVWA_DB_PASSWORD: dvwa_password
      DVWA_DB_DATABASE: dvwa
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - lab-net
    restart: unless-stopped

  # Atacante: OWASP ZAP (Web Proxy e Scanner)
  zap:
    image: zaproxy/zap-stable
    container_name: lab-zap
    ports:
      - "8090:8090" # API ZAP
      - "8081:8081" # Proxy ZAP
    networks:
      - lab-net
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true
    restart: unless-stopped


volumes:
  db_data:

networks:
  lab-net:
    driver: bridge
